heat_template_version: 2014-10-16

description: A template to deploy a load balanced web server

parameters:

  image:
    type: string
    description: Image utilisee pour les serveurs
    default: INF4410-Ubuntu-trusty-mini 
    constraints:
      - custom_constraint: glance.image

  flavor:
    type: string
    description: Flavor utilisee par les serveurs
    default: INF4410-mini
    constraints:
      - custom_constraint: nova.flavor

  subnet_id:
    type: string
    description: Sous-reseau dans lequel le load balancer sera situe
    #A completer

    # Vous pouvez ajouter d'autres paramètres
    # Il faut bien définir les descriptions, les valeurs par default et les contraintes

resources:
  server_nodes:
      type: OS::Heat::ResourceGroup
      properties:
        count: 2
        resource_def:
            type: OS::Nova::Server
            properties:
                key_name: { get_param: key_name }
                image: { get_param: image }
                flavor: { get_param: flavor }
                admin_pass: { get_param: admin_pass }
                networks:
                        - network: { get_param: net1 }
                user_data_format: RAW
                user_data:
                    str_replace:
                    template: |
                        #!/bin/bash
                        wget https://raw.githubusercontent.com/houssemmh/INF8480-TP3/master/server.py
                        python server.py


  mypool:
      type: OS::Neutron::Pool
      propeties:
        lb_method:
        protocol:
        subnet:
        vip:

  myloadbalancer:
      type: OS::Neutron::LoadBalancer
      #A completer

  mymonitor:
      type: OS::Neutron::HealthMonitor
      properties:
      #A completer


outputs:
  pool_ip_address:
    value: {get_attr: [mypool, vip, address]}
    description: The IP address of the load balancing pool
